public enum Direction {NONE, UPLEFT, UP, UPRIGHT, RIGHT, DOWNRIGHT, DOWN, DOWNLEFT, LEFT}
public enum WindSpeed { NORMAL, MIDDLE, STRONG, TYPOON }
public enum DurabilityEvent { INSIDETYPOON_SAIL, INSIDETYPOON_CONTRARYWIND_SAIL, CONTRARYWIND_SAIL, COLLIDE_REEF_BODY, COLLIDE_ISLAND_BODY, COLLIDE_PIRATE_BODY, COLLIDE_SHIP_BODY, INSIDETYPOON_BODY }
public enum Acting { NOTHING, FISHING, REPAIR, DRIVE, SLEEP, EAT }
public enum GameEnding { NONE, ARRIVE, ARRIVE_WORLD, SHIPWRECK, PIRATE, HUNGRY, DEAD}
public enum YachtType { DEFAULT, TYPE_A}
public enum FishingRodType { TYPE_A, TYPE_B}